spring.application.name=account_api

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver

spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true

exchange-rate.api.key=insert_real_key_here
